version: '3'
services:

  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
 
  front:
    build:
      context: ./docker/frontend/
    command: npm run dev
    ports:
       - "8080:8080"
    volumes:
       - ./client:/usr/src/app
